### ISSUE TITLE
Frontend App with this Example

### ISSUE THREAD

**Issue by RayDeanTech** [AzureADQuickStarts/AppModelv2-WebApp-OpenIDConnect-nodejs#50]
@derisen Do you have any recommendations on how to modify this example so that if a Frontend app calls this API, the API would redirect you to "familiar Microsoft" login?  In other words, can this example API forcibly redirect the user to login to set their token before continuing to the original destination (the protected route)?

Here's what I've tried:

I created a `login.ejs`  view, real simple:
```
<h2>Welcome! Please log in.</h2>
<a href="/login">Log In</a>
```

In `app.js`, if the user is NOT authenticated, I try to redirect to that login view:
```
function ensureAuthenticated(req, res, next) {
  if (req.isAuthenticated()) { return next(); }
  // res.redirect('/login');
  
  // res.redirect('/PleaseLogIn');
  // res.status(401).redirect('/PleaseLogIn');
  res.status(401).redirect('http://localhost:3000/PleaseLogIn');
  
};

app.get('/PleaseLogIn', function(req, res){
  res.render('login');
})
```

My Frontend Fetch looks like this:
```
btnCallAPI.addEventListener('click', (e) => {

    fetch('http://localhost:3000/account')
        .then(response => {
            if (response.status === 401) {
                console.log(response)
            } else {
                response.json()
            }
        })
        .then(data => console.log(data))
        .catch((err) => console.log(err));
});
```

**PROBLEMS**
The Frontend gets the redirect (Developer Tools, Network tab), but doesn't _actually_ redirect.  The 401 never comes through, and the console complains about invalid JSON.

I think that the fetch would also need to include the bearer token in the header, too....

Any ideas on how I can get the API to redirect to the "familiar Microsoft" login screen?  AND, how might I maintain the original destination `http://localhost:3000/account` after authentication?

We've got a lot of old Frontend code that I don't want to heavily modify ==> I was really hoping to achieve something like this:  1) API redirects to Microsoft login if not already authenticated; 2) once authenticated, continue to original destination `http://localhost:3000/account`.

Can I even do this all from the Backend?  I'm going to have to modify the Frontend, aren't I? ==>  1) acquire a token, and 2) pass the token?

**Comment by derisen** [comment]
> @derisen Do you have any recommendations on how to modify this example so that if a Frontend app calls this API, the API would redirect you to "familiar Microsoft" login? In other words, can this example API forcibly redirect the user to login to set their token before continuing to the original destination (the protected route)?
> 
> Here's what I've tried:
> 
> I created a `login.ejs` view, real simple:
> 
> ```
> <h2>Welcome! Please log in.</h2>
> <a href="/login">Log In</a>
> ```
> 
> In `app.js`, if the user is NOT authenticated, I try to redirect to that login view:
> 
> ```
> function ensureAuthenticated(req, res, next) {
>   if (req.isAuthenticated()) { return next(); }
>   // res.redirect('/login');
>   
>   // res.redirect('/PleaseLogIn');
>   // res.status(401).redirect('/PleaseLogIn');
>   res.status(401).redirect('http://localhost:3000/PleaseLogIn');
>   
> };
> 
> app.get('/PleaseLogIn', function(req, res){
>   res.render('login');
> })
> ```
> My Frontend Fetch looks like this:
> 
> ```
> btnCallAPI.addEventListener('click', (e) => {
> 
>     fetch('http://localhost:3000/account')
>         .then(response => {
>             if (response.status === 401) {
>                 console.log(response)
>             } else {
>                 response.json()
>             }
>         })
>         .then(data => console.log(data))
>         .catch((err) => console.log(err));
> });
> ```
> 
> **PROBLEMS**
> The Frontend gets the redirect (Developer Tools, Network tab), but doesn't _actually_ redirect. The 401 never comes through, and the console complains about invalid JSON.

@NamedArray This is expected, as express will overwrite 401 with 302 since you are using `.redirect()` after `.status()`. See this [SO thread](https://stackoverflow.com/questions/29481729/chaining-express-js-4s-res-status401-to-a-redirect) for how to get this working. However, keep in mind that you won't be able to do this as a result of a fetch call. The browser will most likely ignore or prevent the redirect response there.

> I think that the fetch would also need to include the bearer token in the header, too....
> 
> Any ideas on how I can get the API to redirect to the "familiar Microsoft" login screen? AND, how might I maintain the original destination `http://localhost:3000/account` after authentication?

This is not a pattern we recommend, as it implies you share server side access tokens with the frontend (when user go to the Microsoft login screen and sign-in, they would be authenticated for the server side app, would get server side tokens, which are different from front-end tokens, which is problematic security-wise).

There is currently an effort in MSAL.js to faciliate such scenarios where authentication between a frontend and a backend app becomes easier, but it's [currently in development](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/3978) and no ETA yet.

> We've got a lot of old Frontend code that I don't want to heavily modify ==> I was really hoping to achieve something like this: 1) API redirects to Microsoft login if not already authenticated; 2) once authenticated, continue to original destination `http://localhost:3000/account`.
> 
> Can I even do this all from the Backend? I'm going to have to modify the Frontend, aren't I? ==> 1) acquire a token, and 2) pass the token?

That's right, sorry : ) You should either go SPA + web API (auth on the frontend, then calling backend with an access token in authorization header) or just web app (auth on the backend, no need for access token afterwards since you're not calling an external web API).

**Comment by RayDeanTech** [comment]
This is much appreciated.  And, it works for us.  I will have two more questions for you, hope that's cool :)
